/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-f372c04de44640fbb6a4f9e4e5845c78
Title: Fox
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from "../assets/3d/wolf.glb";

const Wolf = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());
    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[0.226, 0.001, 0]}
          rotation={[-Math.PI / 2, -0.004, 0]}
          scale={0.01}
        >
          <group
            name="588338cc83ab4499beac6521baf7958afbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="DireWolf">
                  <group name="Geometry">
                    <group
                      name="Dire_wolf"
                      rotation={[Math.PI, 0, Math.PI]}
                      scale={100}
                    />
                  </group>
                  <group name="Main">
                    <group name="DeformationSystem">
                      <group name="Object_9">
                        <primitive object={nodes._rootJoint} />
                        <skinnedMesh
                          name="Object_12"
                          geometry={nodes.Object_12.geometry}
                          material={materials.DireWolf}
                          skeleton={nodes.Object_12.skeleton}
                        />
                        <group
                          name="Object_11"
                          rotation={[Math.PI, 0, Math.PI]}
                          scale={100}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Wolf;
